# Generated by Django 5.2.3 on 2025-06-17 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="User ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Username"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("HOBBY", "Hobby"), ("PRO", "Pro")],
                        default="HOBBY",
                        max_length=50,
                        verbose_name="Plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeployedApp",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Deployed app ID",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployed_apps",
                        to="app.user",
                        verbose_name="App owner",
                    ),
                ),
            ],
        ),
    ]
