# Generated by Django 5.2.3 on 2025-06-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=120, unique=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[("HOBBY", "Hobby"), ("PRO", "Pro")],
                        default="HOBBY",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeployedApp",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployed_apps",
                        to="app.user",
                    ),
                ),
            ],
        ),
    ]
