# Generated by Django 5.2.3 on 2025-07-05 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credits",
            field=models.PositiveIntegerField(default=10, verbose_name="Credits"),
        ),
        migrations.CreateModel(
            name="EmailUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Date")),
                (
                    "sent_count",
                    models.PositiveIntegerField(default=0, verbose_name="Sent count"),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(default=0, verbose_name="Failed count"),
                ),
                (
                    "read_count",
                    models.PositiveIntegerField(default=0, verbose_name="Read count"),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_usage_by_app",
                        to="app.deployedapp",
                        verbose_name="Deployed app",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emails",
                        to="app.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("app", "date")},
            },
        ),
    ]
