# Generated by Django 5.2.3 on 2025-07-06 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user_credits_emailusage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Provider name"
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("SMTP2GO", "SMTP2GO"),
                            ("MAILERSEND", "MAILERSEND"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "master_credentials",
                    models.JSONField(verbose_name="Master credentials"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="credits",
            field=models.PositiveIntegerField(default=2, verbose_name="Credits"),
        ),
        migrations.CreateModel(
            name="AppSendingConfiguration",
            fields=[
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_smtp_credentials",
                        to="app.deployedapp",
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(default=dict),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_smtp_credentials",
                        to="app.user",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_smtp_credentials",
                        to="app.provider",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("app", "user"),
                        name="unique_active_app_user_config",
                    )
                ],
            },
        ),
    ]
