# Generated by Django 5.2.3 on 2025-07-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_provider_alter_user_credits_appsendingconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("SMTP2GO", "SMTP2GO"),
                    ("MAILERSEND", "MAILERSEND"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SentEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=50, verbose_name="Provider")),
                (
                    "time_sent",
                    models.DateTimeField(auto_now_add=True, verbose_name="Time sent"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("queued", "Queued"),
                            ("delivered", "Delivered"),
                            ("bounced", "Bounced"),
                            ("opened", "Opened"),
                        ],
                        default="sent",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "time_read",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Time read"
                    ),
                ),
                (
                    "to_email",
                    models.CharField(max_length=255, verbose_name="Recipient email"),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subject"
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Message ID"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error message"
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_emails_by_app",
                        to="app.deployedapp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_emails_by_user",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-time_sent"],
            },
        ),
    ]
