# Generated by Django 5.2.3 on 2025-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_provider_provider_type_sentemaillog"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentemaillog",
            name="message_tag",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Message tag"
            ),
        ),
    ]
