# Generated by Django 5.2.3 on 2025-07-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_sentemaillog_message_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentemaillog",
            name="message_tag",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Message tag",
            ),
        ),
    ]
