# Generated by Django 5.2.3 on 2025-07-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_sentemaillog_message_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsendingconfiguration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="credentials_format",
            field=models.JSONField(default=dict),
        ),
    ]
