# Generated by Django 5.2.3 on 2025-07-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_appsendingconfiguration_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsendingconfiguration",
            name="provisioning_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appsendingconfiguration",
            name="provisioning_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("pending", "Pending"),
                    ("error", "Error"),
                    ("success", "Success"),
                ],
                default="idle",
                max_length=20,
                verbose_name="Provisioning creds status",
            ),
        ),
        migrations.AlterField(
            model_name="sentemaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("queued", "Queued"),
                    ("delivered", "Delivered"),
                    ("bounced", "Bounced"),
                    ("opened", "Opened"),
                ],
                default="queued",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
